name: Update Events
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests
      - name: Generate events
        env:
          GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
          DEBUG_EVENTS: '1'
        run: |
          python script.py || echo 'script.py exited with code $? (continuing to tests/logging)'
      - name: Run tests
        run: |
          python -m unittest -v || exit 1
      - name: Show diff
        run: |
          git status
          git --no-pager diff --color=always || true
      - name: Commit updated events
        run: |
          if git diff --quiet HEAD -- events.json last_run_raw.json last_run_validated.json 2>/dev/null; then
            echo 'No changes to commit.'
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add events.json || true
            [ -f last_run_raw.json ] && git add last_run_raw.json
            [ -f last_run_validated.json ] && git add last_run_validated.json
            git commit -m "chore: update events.json ($(date -u +%Y-%m-%dT%H:%M:%SZ))" || echo 'Nothing to commit.'
            git push || echo 'Push skipped.'
          fi
      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-json
          path: |
            last_run_raw.json
            last_run_validated.json
          if-no-files-found: ignore
